# Configuration Settings for the Rover Rx

# GNSS/INS Parameters
septentrio_gnss:
  septentrio_gnss_driver:
    ros__parameters:
      device: tcp://192.168.3.1:28784
      
      serial:
        baudrate: 921600
        rx_serial_port: USB1
        hw_flow_control: "off"
      
      stream_device:
        tcp:
          ip_server: ""
          port: 0
        udp:
          ip_server: ""
          port: 0
          unicast_ip: ""
      
      configure_rx: true
      
      login:
        user: ""
        password: ""
      
      custom_commands_file: ""
      
      osnma:
        mode: "loose"
        ntp_server: ""
        keep_open: true
      
      frame_id: gps
      
      aux1_frame_id: gps_base
      
      get_spatial_config_from_tf: true
      
      use_ros_axis_orientation: true
      
      receiver_type: gnss
      
      multi_antenna: true
      
      datum: Default
      
      att_offset:
        heading: 90.0
        pitch: 0.0
      
      ant_type: "Unknown"
      ant_serial_nr: "Unknown"
      ant_aux1_type: "Unknown"
      ant_aux1_serial_nr: "Unknown"
      
      polling_period:
        pvt: 50
        rest: 0
      
      ntrip_input: "/ntrip_client/rtcm"
      # time
      use_gnss_time: false
      ntp_server: true
      ptp_server_clock: false
      latency_compensation: true
      
      # RTK
      rtk_settings:  
        ntrip_1:
          id: ""
          caster: ""
          caster_port: 2101
          username: ""
          password: ""
          mountpoint: ""
          version: "v2"
          tls: false
          fingerprint: ""
          rtk_standard: "auto"
          send_gga: "auto"
          keep_open: true
        ip_server_1:
          id: ""
          port: 0
          rtk_standard: "auto"
          send_gga: "auto"
          keep_open: true
        serial_1:
          port: ""
          baud_rate: 921600
          rtk_standard: "auto"
          send_gga: "auto"
          keep_open: true
      
      publish:
        # For both GNSS and INS Rxs
        auto_publish: false
        publish_only_valid: false
        navsatfix: true
        gpsfix: true
        gpgga: true
        gprmc: true
        gpst: true
        measepoch: true
        pvtcartesian: true
        pvtgeodetic: false
        basevectorcart: false
        basevectorgeod: false
        poscovcartesian: true
        poscovgeodetic: true
        velcovcartesian: false
        velcovgeodetic: true
        atteuler: true
        attcoveuler: true
        pose: true
        twist: true
        diagnostics: true
        aimplusstatus: true
        galauthstatus: false
        # For GNSS Rx only
        gpgsa: false
        gpgsv: false
      
      # logger
      
      activate_debug_log: false